PREFIX dbpprop:<http://dbpedia.org/property/>
PREFIX dbpowl:<http://dbpedia.org/ontology/>
PREFIX dbpresource:<http://dbpedia.org/resource/>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
SELECT ?entity ?name
WHERE{
    ?entity a dbpowl:Book;
        dbpprop:name ?name.
}
